### ISSUE TITLE
Idle strategy always loaded from cache despite hard reload

### ISSUE THREAD

**Issue by iniznet** [Accudio/async-alpine#23]
I found out that when the component strategy is set to `idle` it always loaded from the cache despite me pressing hard reload in the browser. Any idea?

![image](https://user-images.githubusercontent.com/34362833/193298342-0db267ab-9645-4c65-88e2-ad479cc03a85.png)

**Comment by Accudio** [comment]
Could you make a reduced test case? I'm not seeing the same issue in [tests/strategies/idle](https://github.com/Accudio/async-alpine/blob/main/tests/strategies/idle.html) but it may be depending on implementation.

Also helpful would be how you're loading Async Alpine (imported into bundle, script, cdn etc), how you specify the component download (dynamic import or ax-load-src) and browser details.

Thanks!

**Comment by iniznet** [comment]
After some review, I'm unable to reproduce the issue with my test case, so I think there's something that went wrong within the WordPress environment like the default cache control policy. I will close the issue as it's not related to the library.
