### ISSUE TITLE
Cannot reference "$wire" outside a Livewire component

### ISSUE THREAD

**Issue by JohnnyMaynne** [Accudio/async-alpine#28]
Laravel v9.52.0
Livewire v2.12.0
Alpine js  v3.10.3
Async-alpine v1.0.0
Vite v3.2.5

When I try to use the $wire object, I get an error . Sample code below.

Component js: 
<img width="624" alt="image" src="https://user-images.githubusercontent.com/26120256/220600480-ba5fb255-c19b-4309-80aa-8e1c688b5e26.png">

Register js components: 
<img width="718" alt="image" src="https://user-images.githubusercontent.com/26120256/220597604-5e764811-e408-416d-af04-a829801bf2e8.png">

Blade component:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/26120256/220597375-95d6731c-1af0-4d1e-8d60-c011a767178c.png">

Error:
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/26120256/220597744-4cae1da6-2f6d-44af-a1d1-67dbdd37e51f.png">
<img width="652" alt="image" src="https://user-images.githubusercontent.com/26120256/220600746-3006fed3-fdcb-44bc-97cc-eeffe602b877.png">

**Comment by Accudio** [comment]
Hey!

I'm afraid I have no experience with Livewire so I'm not in a good position to be able to investigate this at the moment.

Would you be able to put together an example repo that's as simple as possible? Just the bare minimum required to replicate this issue without any extra libraries or anything.

That would be very helpful for if I get the time to look into this or if someone else with some Livewire knowledge wants to help.

**Comment by JohnnyMaynne** [comment]
> Hey!
> 
> I'm afraid I have no experience with Livewire so I'm not in a good position to be able to investigate this at the moment.
> 
> Would you be able to put together an example repo that's as simple as possible? Just the bare minimum required to replicate this issue without any extra libraries or anything.
> 
> That would be very helpful for if I get the time to look into this or if someone else with some Livewire knowledge wants to help.

I will try to restore the problem in the demo repository in the coming days 👍🏻

**Comment by iniznet** [comment]
To make this issue not stale, `$wire` only works within an AlpineJS component.
Reference: https://laravel-livewire.com/docs/2.x/alpine-js

This is just my guess, but it usually occurs if we call them from outside the component.

In essence, you need to enclose the async-alpine component within another blank component. This is because the component hasn't initialized yet, so `$wire` doesn't exist in the current state.

With Livewire v3 now stable, integrating async-alpine into live is much easier, as it now bundles alpinejs and exposes them together.
```js
// resources/js/app.js
import './bootstrap';

import AsyncAlpine from 'async-alpine';
import { Livewire, Alpine } from '../../vendor/livewire/livewire/dist/livewire.esm';

AsyncAlpine.init(Alpine);
AsyncAlpine.alias((name) => import(`./components/${name}.module.js`));
AsyncAlpine.start();
Livewire.start();

```

```js
// resources/js/components/counterlog.module.js
export default function counterlog({ number }) {
    return {
        number,
        init() {
            // will log returned @entangle() object,
            // but still able to get the initialValue from that object
            console.log(number)

            this.$watch('number', (value) => {
                console.log(value)
            });
        }
    }
}
```

```php
<?php
//app/Livewire/Counter.php
namespace App\Livewire;

use Livewire\Component;

class Counter extends Component
{
    public $count = 1;

    public function increment()
    {
        $this->count++;
    }

    public function decrement()
    {
        $this->count--;
    }

    public function render()
    {
        return view('livewire.counter');
    }
}
```

```blade
{{--resources/views/livewire/counter.blade.php--}}
<div>
    <h1>{{ $count }}</h1>

    <div
        x-ignore
        ax-load
        x-data="counterlog({
            {{-- Use @entangle rather than $wire --}}
            number: @entangle('count'),
        })"
    >
        <span x-text="number"></span>
    </div>

    <button wire:click="increment">+</button>

    <button wire:click="decrement">-</button>
</div>
```

**Comment by danharrin** [comment]
https://github.com/filamentphp/filament heavily uses Async Alpine with Livewire, without issues. `$wire` works just fine, so I think this issue can be closed.

**Comment by Accudio** [comment]
Thank you both @iniznet and @danharrin. I'm going to mark this as closed in light of the recent comments.
