### ISSUE TITLE
Enable multiple matches in AsyncAlpine.alias()

### ISSUE THREAD

**Issue by scruffymongrel** [Accudio/async-alpine#32]
I have components organised as follows:

```
components/
  Button/
    Button.island.js
    Button.jsx
 ```

In my Vite entry file, I'm using `AsyncAlpine.alias('components/[name]/[name].island.js')`.

As only the first instance of `[name]` is replaced, I get a 404 on http://localhost:5173/components/Button/[name].island.js.

If I remove the second instance of `[name]` and rename `Button.island.js` to `island.js`, everything works as expected.

Would you be happy to enable replacement of multiple instances of `[name]` in `AsyncAlpine.alias()`?

**Comment by Accudio** [comment]
Yep absolutely. That's something I missed due to using `.replace` instead of `.replaceAll`.

I can update next week, or you're welcome to make a PR with that change.

**Comment by scruffymongrel** [comment]
Excellent. Have created a PR (#34). Thanks :)
