### ISSUE TITLE
Alpine Expression Error: w.bind is not a function

### ISSUE THREAD

**Issue by fahrim** [Accudio/async-alpine#45]
Hi guys, I am running my function as in the async-alpine docs but I am encountering this error.

`app-WoaEjcF-.js:2 Alpine Expression Error: w.bind is not a function`
`app-WoaEjcF-.js:6 Uncaught TypeError: w.bind is not a function`
![Ekran görüntüsü 2024-10-27 012954](https://github.com/user-attachments/assets/fafb74e2-e41b-4aaa-a0d8-68b0d90cb1d1)
![Ekran görüntüsü 2024-10-27 013141](https://github.com/user-attachments/assets/de25277c-50d9-4cb4-8d2e-abb8154d65fb)
![Ekran görüntüsü 2024-10-27 013301](https://github.com/user-attachments/assets/6d412493-4d29-41f9-898b-b8a281336de0)

I am getting the same error in more than one function I use Async.

![Ekran görüntüsü 2024-10-27 011855](https://github.com/user-attachments/assets/008bb5a6-0bbd-4a60-a622-177036d9a21c)
![Ekran görüntüsü 2024-10-27 011926](https://github.com/user-attachments/assets/348ac123-4b7c-40ac-b8d6-12425c0b8c95)

 I am using it with Livewire and I have made the initializer arrangement as in "https://livewire.laravel.com/docs/installation#manually-bundling-livewire-and-alpine".
 
 admin/app.js
![Ekran görüntüsü 2024-10-27 013500](https://github.com/user-attachments/assets/a190612d-0e43-402b-89a9-5a35d62e6322)

Update: 
When I run it with "`npm run dev`" it worked fine (vite) 
When I build it with "`npm run build`" it doesn't work fine (vite build)

**Comment by Accudio** [comment]
Hi @fahrim, this looks like it's specifically related to the build setup and how that `Vite::asset` function processes assets.

Could you please provide a reduced test case repo where I can replicate this?
I'm not very familiar with Livewire or Vite so will need that yo dig into it.

It may be worth considering trying [Data components](https://async-alpine.dev/docs/usage/#data) — that is how I've had the most success with build tools like Vite in the past.

**Comment by fahrim** [comment]
> @Accudio 

Sorry I don't have enough experience to create a test. I'm working on the problem, as far as I understand there is no problem with this asyn-alpine work, I must be doing something wrong somewhere else. I focused on two issues; Maybe there is a problem with the JS Loading order or maybe I have a problem with the vite:asset loading as you mentioned.

[https://filamentphp.com/docs/3.x/support/assets#asynchronous-alpinejs-components](https://filamentphp.com/docs/3.x/support/assets#asynchronous-alpinejs-components) There is a similar usage here and it says that the js code should be built with esbuild before using it. I don't know why this is necessary, but I can try it in my own code as a final plan.

**Comment by fahrim** [comment]
I found out exactly what was causing the problem. Vite (in vite.config.js) was not building the js assets I specified, that is, the "public/build/assets/example.js" (for Laravel-vite) content was empty after the build. I found out that the reason for this was that vite was processing es6 compatible codes.

Therefore, the codes are made to work by subjecting them to the esbuild process mentioned in the Filament documentation that I mentioned in the previous comment.
I read in a solution discussion that vite does not compile unused codes. Therefore, a solution could be to assign your unbuilt function to a global function with "window." and have vite compile your code. These methods were not very healthy for me, maybe my desk was too messy.

We are divided into two ways for the solution:
Either to overcome Vite's build problem, or to add our js code to a static location (cdn or /public). In terms of overcoming the build problem of Vite, using Async-alpine with Data Components as @Accudio mentioned gives excellent results. Because Vite already understands that your code is being used and returns the build result as positive and at the same time you do not have to specify it in the assets section on vite.config.js. Vite detects that you are using it and compiles it for you.

@Accudio, thank you for your help. I hope it helps those who are stuck on such a topic.

**Comment by Accudio** [comment]
@fahrim Ah, good to know!

Yeah, when dealing with Vite and other build tools I've found that sticking with data components and dynamic imports is way easier.

I'm glad that's working out better for you and thanks for the context for others.
